//
//  Filters.swift
//  VirtualCameraSampleController
//
//  Created by Jaiten Gill on 2021-03-03.
//

class Filters: NSObject {
    
    var filters: [FilterObject] = [FilterObject]()

    override init() {
        let blackAndWhite = FilterObject(name: "B&W", path: "b&w", image: NSImage(named: "b&w")!)
        let blueLaser = FilterObject(name: "Blue Laser", path: "blue_laser", image: NSImage(named: "blue_laser")!)
        let caustics = FilterObject(name: "Caustics", path: "caustics", image: NSImage(named: "caustics")!)
        let chromatic = FilterObject(name: "Chromatic Aberration", path: "chromatic_aberration", image: NSImage(named: "chromatic_aberration")!)
        let clubPartyLights = FilterObject(name: "Club Party Lights", path: "club_party_lights", image: NSImage(named: "club_party_lights")!)
        let confetti = FilterObject(name: "Confetti", path: "confetti", image: NSImage(named: "confetti")!)
        let displacedGlow = FilterObject(name: "Displaced Glow", path: "displaced_glow", image: NSImage(named: "displaced_glow")!)
        let dreamyBloom = FilterObject(name: "Dreamy Bloom", path: "dreamy_bloom", image: NSImage(named: "dreamy_bloom")!)
        let fireflies = FilterObject(name: "Fireflies", path: "fireflies", image: NSImage(named: "fireflies")!)
        let glitchV2 = FilterObject(name: "Glitch V2", path: "glitch_v2", image: NSImage(named: "glitch_v2")!)
        let glitch = FilterObject(name: "Glitch", path: "glitch", image: NSImage(named: "glitch")!)
        let glitter = FilterObject(name: "Glitter", path: "glitter", image: NSImage(named: "glitter")!)
        let glowyGoo = FilterObject(name: "Glowy Goo", path: "glowy_goo", image: NSImage(named: "glowy_goo")!)
        let greenLaser = FilterObject(name: "Green Laser", path: "green_laser", image: NSImage(named: "green_laser")!)
        let lensFlare = FilterObject(name: "Lens Flare", path: "lens_flare", image: NSImage(named: "lens_flare")!)
        let matrix = FilterObject(name: "Matrix", path: "matrix", image: NSImage(named: "matrix")!)
        let nightVision = FilterObject(name: "Night Vision", path: "night_vision", image: NSImage(named: "night_vision")!)
        let oldFilmDust = FilterObject(name: "Old Film Dust", path: "old_film_dust", image: NSImage(named: "old_film_dust")!)
        let oldFilm = FilterObject(name: "Old Film", path: "old_film", image: NSImage(named: "old_film")!)
        let onlyReds = FilterObject(name: "Only Reds", path: "only_reds", image: NSImage(named: "only_reds")!)
        let overlayFire = FilterObject(name: "Overlay Fire", path: "overlay_fire", image: NSImage(named: "overlay_fire")!)
        let paper = FilterObject(name: "Paper", path: "paper", image: NSImage(named: "paper")!)
        let smoke = FilterObject(name: "Smoke", path: "smoke", image: NSImage(named: "smoke")!)
        let stars = FilterObject(name: "Stars", path: "stars", image: NSImage(named: "stars")!)
        let staticStrong = FilterObject(name: "Static Strong", path: "static_strong", image: NSImage(named: "static_strong")!)
        let static2 = FilterObject(name: "Static", path: "static", image: NSImage(named: "static")!)
        let technical = FilterObject(name: "Technical", path: "technical", image: NSImage(named: "technical")!)
        let thermalVision = FilterObject(name: "Thermal Vision", path: "thermal_vision", image: NSImage(named: "thermal_vision")!)
        let trippy = FilterObject(name: "Trippy", path: "trippy", image: NSImage(named: "trippy")!)
        let velvet = FilterObject(name: "Velvet", path: "velvet", image: NSImage(named: "velvet")!)
        let vhs = FilterObject(name: "VHS", path: "vhs", image: NSImage(named: "vhs")!)
        let none = FilterObject(name: "None", path: "none", image: NSImage(named: "vhs")!)

        self.filters.append(blackAndWhite)
        self.filters.append(blueLaser)
        self.filters.append(caustics)
        self.filters.append(chromatic)
        self.filters.append(clubPartyLights)
        self.filters.append(confetti)
        self.filters.append(displacedGlow)
        self.filters.append(dreamyBloom)
        self.filters.append(fireflies)
        self.filters.append(glitchV2)
        self.filters.append(glitch)
        self.filters.append(glitter)
        self.filters.append(glowyGoo)
        self.filters.append(greenLaser)
        self.filters.append(lensFlare)
        self.filters.append(matrix)
        self.filters.append(nightVision)
        self.filters.append(oldFilmDust)
        self.filters.append(oldFilm)
        self.filters.append(onlyReds)
        self.filters.append(overlayFire)
        self.filters.append(paper)
        self.filters.append(smoke)
        self.filters.append(stars)
        self.filters.append(staticStrong)
        self.filters.append(static2)
        self.filters.append(technical)
        self.filters.append(thermalVision)
        self.filters.append(trippy)
        self.filters.append(velvet)
        self.filters.append(vhs)
        self.filters.append(none)
    }
}
